FROM pangenome/pggb:latest

# Ibstall pafgnostics
RUN git clone https://github.com/AndreaGuarracino/pafgnostic && cd pafgnostic && cargo install --force --path .

WORKDIR /
COPY bin.docker/mash /usr/local/bin
RUN ln -s /opt/venv/bin/python /usr/bin
ENV PYTHONPATH="/opt/venv/lib/python3.11/site-packages:$PYTHONPATH"
COPY bin.docker/preprocess.py /bin/
COPY bin.docker/editpaf.py /bin/
